config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'  #Dashboard 
    resources :admins  #, only: [:index, :edit, :update, :new, :create, :destroy ]  # controle administradores
    resources :subjects
    resources :questions # 
    # no RESOURCES, so nao vamos querer o DELETE, poderiamos fazer tambem como esta abaixo: PJCS
    # resources :admins, except: [:destroy ]

  end

  devise_for :admins
  devise_for :users 

  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions 
end

app/controllers/admins_backoffice/admins_controller.rb
#class AdminsBackoffice::AdminsController < ApplicationController
class AdminsBackoffice::AdminsController < AdminsBackofficeController

    before_action :verificaSenhaEmBranco, only: [:update]
    before_action :set_admin_find_jecasi, only: [:edit, :update, :destroy]


    def index
        #@admins = Admin.all 
        #-- foi adicionado o "page params[:page]" para pagina a lista de adm- PJCS 
        @admins = Admin.all.page(params[:page])
        #-- pra commpletar a paginação, tem que colocar o "<%= paginate @admins %>"  no:
        #-- app\views\admins_backoffice\admins\index.html.erb
        # pra controlar o qtd de itens por pagina, vamos no: app\models\admin.rb
    end

    def new
        @admin = Admin.new 
    end 

    def create
        @admin = Admin.new(params_admin)
        if @admin.save()
            # As informações vinheram do: app\views\admins_backoffice\admins\new.html.erb
            # se for TRUE, vamos voltar para tela principal do ADMIN - PJCS
            redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso!"
        else 
            # se for FALSE, volta pra a EDIÇÃO - PJCS 
            render :edit 
        end
    
    end 

    def edit
        #  o ID veio do: app\views\admins_backoffice\admins\index.html.erb - PJCS 
        # @admin= Admin.find(params[:id]) -> passou a ser chamado no BEFORE_ACTION - PJCS
    end 

    def update
        # o ID veio do: app\views\admins_backoffice\admins\edit.html.erb - PJCS 
        # @admin = Admin.find(params[:id]) -> passou a ser chamado no BEFORE_ACTION - PJCS
        if @admin.update(params_admin)
            # se for TRUE, vamos voltar para tela principal do ADMIN - PJCS
            redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso!"
        else 
            # se for FALSE, volta pra a EDIÇÃO - PJCS 
            render :edit 
        end
    end

    def destroy
        # o ID veio do: app\views\admins_backoffice\admins\index.html.erb - PJCS 
        # @admin = Admin.find(params[:id]) -> passou a ser chamado no BEFORE_ACTION - PJCS
        if @admin.destroy
            # se for TRUE, vamos voltar para tela principal do ADMIN - PJCS
            redirect_to admins_backoffice_admins_path, notice: "Administrador excluido com sucesso!"
        else 
            # se for FALSE, volta pra a EDIÇÃO - PJCS 
            render :index
        end

    end 

    private

    def verificaSenhaEmBranco 
        if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
            params[:admin].extract!(:password, :password_confirmation)
        end 
    end

    def params_admin
         # PJCS -  vamos autorizar  o UPDATE dos dados abaixo
         params_admin = params.require(:admin).permit(:email, :password, :password_confirmation)
    end 

    def set_admin_find_jecasi  
        #  o ID veio do: app\views\admins_backoffice\admins\index.html.erb - PJCS 
        @admin= Admin.find(params[:id])
    end 
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController

    before_action :set_question_find_jecasi, only: [:edit, :update, :destroy]

    before_action :get_subjects_jecasi, only: [:edit, :new]

    
    def index
        @questions = Question.includes(:subject).order(:description).page(params[:page])
    end

    def new
        @question = Question.new 
    end 

    def create
        @question = Question.new(params_question)
        if @question.save()
            redirect_to admins_backoffice_questions_path, notice: "Questão cadastrado com sucesso!"
        else
            render :edit 
        end
    
    end 

    def edit 
    end 

    def update

        if @question.update(params_question)
            redirect_to admins_backoffice_questions_path, notice: "Questão atualizado com sucesso!"
        else 
            render :edit 
        end
    end

    def destroy
        if @question.destroy
            # se for TRUE, vamos voltar para tela principal do ADMIN - PJCS
            redirect_to admins_backoffice_questions_path, notice: "Questão excluido com sucesso!"
        else 
            # se for FALSE, volta pra a EDIÇÃO - PJCS 
            render :index
        end

    end 

    private


    def params_question
         # PJCS -  vamos autorizar  o UPDATE dos dados abaixo
         params_question = params.require(:question).permit(:description, :subject_id, 
                         answers_attributes: [:id, :description, :correct, :_destroy]))
         
    end 

    def set_question_find_jecasi  
        #  o ID veio do: app\views\admins_backoffice\admins\index.html.erb - PJCS 
        @question= Question.find(params[:id])
    end 

    def get_subjects_jecasi
        @subjects= Subject.all
    end
end 

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController

    before_action :set_subject_find_jecasi, only: [:edit, :update, :destroy]


    def index
        @subjects = Subject.all.order(:description).page(params[:page])
    end

    def new
        @subject = Subject.new 
    end 

    def create
        @subject = Subject.new(params_subject)
        if @subject.save()
            redirect_to admins_backoffice_subjects_path, notice: "Areas/Assuntos cadastrado com sucesso!"
        else
            render :edit 
        end
    
    end 

    def edit

    end 

    def update

        if @subject.update(params_subject)
            redirect_to admins_backoffice_subjects_path, notice: "Areas/Assuntos atualizado com sucesso!"
        else 
            render :edit 
        end
    end

    def destroy
        if @subject.destroy
            # se for TRUE, vamos voltar para tela principal do ADMIN - PJCS
            redirect_to admins_backoffice_subjects_path, notice: "Areas/Assuntos excluido com sucesso!"
        else 
            # se for FALSE, volta pra a EDIÇÃO - PJCS 
            render :index
        end

    end 

    private


    def params_subject
         # PJCS -  vamos autorizar  o UPDATE dos dados abaixo
         params_subject = params.require(:subject).permit(:description)
    end 

    def set_subject_find_jecasi  
        #  o ID veio do: app\views\admins_backoffice\admins\index.html.erb - PJCS 
        @subject= Subject.find(params[:id])
    end 
end

app/controllers/admins_backoffice/welcome_controller.rb
#class AdminsBackoffice::WelcomeController < ApplicationController
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  #layout 'admins_backoffice'
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object=nil ,method=nil)
        if object && method
            #PJCS  vai pegar o "method" no:config\locales\models.pt-BR.yml
            object.model.human_attribute_name(method)
        else 
            "Informe os Parametros Corretamente!"
        end
    end
end

app/views/admins_backoffice/subjects/edit.html.erb
<!-- chama o form no: app\views\admins_backoffice\admins\shared\_form.html.erb -->
<%= render partial: 'admins_backoffice/subjects/shared/form',
            locals: {action_message_jecas: 'Edição de Assuntos/Areas',
                     action_botao_jecas: 'Alterar Dados' } %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">  Lista dos Assuntos/Areas </h1>
    </div>
    <!-- /.col-lg-12 -->
</div>





<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover ">
        <thead>
            <tr>
                <!--  PJCS - vamos pegar os titulos direto do: 
                  app\helpers\admins_backoffice_helper.rb  e de la no:
                  config\locales\models.pt-BR.yml

                <th>Id</th>
                <th>Descrição</th>
                <th>
                --> 

                <th> <%= translate_attribute(@subjects, :id) %> 
                <th> <%= translate_attribute(@subjects, :description) %> 
                <th>

                    <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle btn-lg" do %>
                        <i class="fa fa-plus"></i>
                    <% end %> 
                
                </th>
            </tr>
        </thead>
        
        <tbody>

            <% @subjects.each do |subject| %>
            <tr>
                <td><%= subject.id %></td>
                <td><%= subject.description %></td>
                <td style="width: 120px">

                    <!--
                     Este ID sera recebido no: \app\controllers\admins_backoffice\admins_controller.rb - PJCS 
                    -->
                    <%= link_to edit_admins_backoffice_subject_path(subject.id), class:"btn btn-primary btn-circle" do %>
                        <i class="fa fa-edit"></i>
                    <% end %> 

                    <%= link_to admins_backoffice_subject_path(subject.id), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: "Excluir Assunto/Area?"} do %>
                        <i class="fa fa-minus"></i>
                    <% end %>

                </td>
            </tr>
            <% end %>
        </tbody>
    </table>

    <!-- tem que adicionar no: app\controllers\admins_backoffice\admins_controller.rb, no index 
       o parametro "page params[:page] pra concluir a paginação da lista" - PJCS 
         pra controlar o qtd de itens por pagina, vamos no: app\models\admin.rb
    -->
    <div class= "text-center">
        <%= paginate @subjects %>
    </div>

</div>

app/views/admins_backoffice/subjects/new.html.erb
<!-- chama o form no: app\views\admins_backoffice\admins\shared\_form.html.erb -->
<%= render partial: 'admins_backoffice/subjects/shared/form',
            locals: {action_message_jecas: 'Cadastro de Assuntos/Areas',
                     action_botao_jecas: 'Gravar Dados' } %>