config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'  #Dashboard 
    resources :admins  #, only: [:index, :edit, :update, :new, :create, :destroy ]  # controle administradores
    resources :subjects
    resources :questions # 
    # no RESOURCES, so nao vamos querer o DELETE, poderiamos fazer tambem como esta abaixo: PJCS
    # resources :admins, except: [:destroy ]

  end

  devise_for :admins
  devise_for :users 

  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #paginação kaminari - PJCS
  paginates_per 15

end
 

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
	before_action :authenticate_user!
	layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object=nil ,method=nil)
        if object && method
            #PJCS  vai pegar o "method" no:config\locales\models.pt-BR.yml
            object.model.human_attribute_name(method)
        else 
            "Informe os Parametros Corretamente!"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/admins/shared/_form.html.erb
<!-- 
a variavel @admin foi carregada em:\app\controllers\admins_backoffice\admins_controller.rb - PJCS 
-->

<!--
<%= @admin.inspect %>
-->

<!-- PJCS
<div class="row">

-->

<!-- form chamado no: app\views\admins_backoffice\admins\edit.html.erb
                e no: app\views\admins_backoffice\admins\new.html.erb
--> 

    <% if @admin.errors.any? %> 

        <!-- mensagens de alerta, tenho mais exemplos em MINHAS ANOTAÇÔES - PJCS -->
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <% @admin.errors.full_messages.each do |message| %>
                    <li>  <%= message %> </li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="col-md-12">
        <h1 class="page-header"> <%= action_message_jecasi %> </h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="panel-body">
    
                <!--  este forme foi substituido pelo form_with - PJCS 
                <form role="form">
                -->
                <!-- por padrao, o form abaixo trabalha com Java Script, como quero trabalhar com 
                     html, vamos colocar a tag: Local: true 
                -->
        <%= form_with(model: [ :admins_backoffice, @admin ], local: true) do|form| %>
           
            <div class="form-group" >
                <div class="row">
                    <div class="col-md-3">
                        <!-- PJCS - vamos alterar para RUBY
                        <label>Id:</label>
                        <input class="form-control" placeholder="Enter text">
                        -->
                        
                        <%= form.label :id %>
                        <%= form.text_field :id, class:"form-control", placeholder:"Id do Adm ", readonly:"true" %>
                        
                    </div>
                </div>
            </div>
            
            <div class="form-group" >
                <div class="row">
                    <div class="col-md-9">
                        <!-- PJCS - vamos alterar para RUBY
                        <label>Email:</label>
                        <input class="form-control" placeholder="Enter text">
                        -->
                        
                        <%= form.label :email %>
                        <%= form.text_field :email, class:"form-control", placeholder:"Email do Adm " %>

                    </div>
                </div>
            </div>

            <div class="form-group" >
                <div class="row">
                    <div class="col-md-6">
                        <!-- PJCS - vamos alterar para RUBY
                        <label>Senha:</label>
                        <input class="form-control" placeholder="Enter text">
                        --> 

                        <%= form.label :password %>
                        <%= form.password_field :password, class:"form-control", placeholder:"Senha do Adm " %>

                    </div>
                </div>
            </div>

            <div class="form-group" >
                <div class="row">
                    <div class="col-md-6">
                        <!-- PJCS - vamos alterar para RUBY
                        <label>Confirmação da Senha:</label>
                        <input class="form-control" placeholder="Enter text">
                        --> 

                        <%= form.label :password_confirmation %>
                        <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Senha de Confirmação " %>

                    </div>
                </div>
            </div>
                    

                    <!-- type="submit" - envia os dados inseridos no form - PJCS -->
            <button type="submit" class="btn btn-primary"> <%= action_botao_jecasi %> </button>
                    
                
                    
        <% end %>
    </div>

<!-- PJCS
</div>
--> 

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
 <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application' %>
     <!-- chamado no : app/assets/stylesheets/admins_backoffice.scss - PJCS -->
    <%= stylesheet_link_tag    'admins_backoffice' %>  
   


 </head>




 <body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">

        </div>
        <div class="sidebar-brand-text mx-3">Grupo Paulo Cardoso </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard PJCS ----------------------->
      <li class="nav-item">   
          <%= link_to admins_backoffice_welcome_index_path, class:"nav-link" do %>
            <span> Página Principal </span>
          <% end %>  
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item Administradores PJCS--------------------->

      <li class="nav-item">   
          <%= link_to admins_backoffice_admins_path, class:"nav-link" do %>
            <span> Administradores </span> 
          <% end %>  
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item Areas/assuntos PJCS--------------------->

      <li class="nav-item">   
          <%= link_to admins_backoffice_subjects_path, class:"nav-link" do %>
            <span> Areas / assuntos </span> 
          <% end %>  
      </li>

      <hr class="sidebar-divider my-0">

      <!-- Nav Item de QUESTOES PJCS--------------------->

      <li class="nav-item">   
          <%= link_to admins_backoffice_questions_path, class:"nav-link" do %>
            <span> Questões / Perguntas </span> 
          <% end %>  
      </li>
        

      <!-- Divider -->
      <hr class="sidebar-divider my-0">


    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->


            <!-- Nav Item - Messages -->
 

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Paulo Cardoso</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
               
  
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                      Sair 
                  <%  end %>  
                  
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <!-- <h1 class="h3 mb-4 text-gray-800">Grupo Paulo Jecasi</h1>  --> 
          
          <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->

  
  <%= javascript_include_tag 'application' %>
  <!-- Chamado no: app\assets\javascripts\admins_backoffice.coffee -->
  <%= javascript_include_tag 'admins_backoffice' %>

<% if  notice %>
  <%= javascript_tag do %>
     $.bootstrapGrowl("<%= notice %>", {
     type: 'success', // (null, 'info', 'danger', 'success')
     align: 'center', // ('left', 'right', or 'center')
     allow_dismiss: true, // If true then will display a cross to close the popup.
     stackup_spacing: 15 // spacing between consecutively stacked growls.
     });
  <% end %>
<% end %>



 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1> LAYOUT PADRAO (aplication) </h1> 
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1> LAYOUT SITE </h1> 
    <%= yield %>
  </body>
</html>