config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'  #Dashboard 
    resources :admins  #, only: [:index, :edit, :update, :new, :create, :destroy ]  # controle administradores
    resources :subjects
    resources :questions # 
    # no RESOURCES, so nao vamos querer o DELETE, poderiamos fazer tambem como esta abaixo: PJCS
    # resources :admins, except: [:destroy ]

  end

  devise_for :admins
  devise_for :users 

  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins_backoffice/welcome_controller.rb
#class AdminsBackoffice::WelcomeController < ApplicationController
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  #layout 'admins_backoffice'
  def index
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index  SITE - JECASI </h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if user_signed_in? %>

	<p> Usuario ESTÁ logado / <%= current_user.email %>  </p>
	
<% else %>

    <p> Usuario NÃO ESTÁ logado </p>

<% end %> 


<% if admin_signed_in? %>

	<p> Administador ESTÁ logado / <%= current_admin.email %> </p>
	
<% else %>

    <p> Administrador NÃO ESTÁ logado </p>

<% end %> 

<h1>
  <%= link_to ' Usuario       ', users_backoffice_welcome_index_path %>
</h1>

<h1>
  <%=  link_to ' Administração ', admins_backoffice_welcome_index_path %>
</h1>